### ISSUE TITLE
Because every version of flutter_test from sdk depends on pedantic 1.5.0 and mailer >=3.0.0 depends on pedantic ^1.7.0, flutter_test from sdk is incompatible with mailer >=3.0.0. So, because shut_down_now depends on both mailer ^3.0.0 and flutter_test any from sdk, version solving failed. pub get failed (1)

### ISSUE THREAD

**Issue by Prn-Ice** [kaisellgren/mailer#102]
flutter packages get fails with the error above, do I need to use a previous version

**Comment by Prn-Ice** [comment]
It was fixed with flutter update

**Comment by close2** [comment]
Thanks for the feedback.  I closed this issue because I had relaxed the pedantic version in version 3.0.1 assuming that this would fix this issue.

In any case.  Good to know that it works now.
