### ISSUE TITLE
Question in multiple attachment

### ISSUE THREAD

**Issue by edufpin** [kaisellgren/mailer#105]
First of all, thanks for the plugin.
I have a question that i didnt managed to resolve by myself, i have multiple files that are already processed and i want to send they as an attachment, how can i manage to do that? There is a way to pass a list of files?

Code that sends only one file:
      ..attachments.add(new FileAttachment(_firstImageFile));

Thanks!

**Comment by close2** [comment]
just repeat the line, or use `addAll`

`..attachments` is a `list` of Attachments.
