### ISSUE TITLE
Socket was closed even though a response was expected

### ISSUE THREAD

**Issue by NTMS2017** [kaisellgren/mailer#106]
I am using 'mailer: ^2.5.0' and it was working last 2 months but suddenly I am keep getting below error. Any idea?

**SMTP_ERROR: SMTP error: Socket was closed even though a response was expected.**

```
  final smtpServer = new SmtpServer('mail.mycompany.com',
          username: _username,
          password: _password,
          port: 25,
          ignoreBadCertificate: true,
          ssl: false,
          allowInsecure: true);
```

**Comment by close2** [comment]
Please enable logging output:
```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```
The log output may contain your credentials.  Please obfuscate them (especially the lines around `AUTH`).

version 2.5.1 shouldn't contain any changes which explain your behavior.

**Comment by husseinYY** [comment]
I'm having this issure too! 

Here is my code:-

`sendEmail() async {
  final smtpServer = yahoo(yahooEmail, yahooPassword);

  final message = Message()
    ..from = Address('email@yahoo.com', 'usernamehere')
    ..recipients.add('email@gmail.com')
    ..subject = 'Test Dart Mailer library :: 😀 :: ${DateTime.now()}'
    ..text = 'This is the plain text.\nThis is line 2 of the text part.'
    ..html = "<h1>Test</h1>\n<p>Hey! Here's some HTML content</p>";

  try {
    final sendReport = await send(message, smtpServer);
    print('Message sent: ' + sendReport.toString());
  } on MailerException catch (e) {
    print('Message not sent. $e');
    for (var p in e.problems) {
      print('Problem: ${p.code}: ${p.msg}');
    }
  }
}`

Any ideas?

**Comment by close2** [comment]
@husseinYY Please enable logging as mentioned in my previous comment.

**Comment by OlegAlexander** [comment]
Hello,

I ran into this error today when migrating to null safety. I'm using mailer 4.0.0. The code sends an email when I'm on `sdk: '>=2.10.0 <3.0.0'`. However, as soon as I switch to `sdk: '>=2.12.0 <3.0.0'` I get the `Socket was closed even though a response was expected` error. 

Note, it just so happened that my code didn't require any null safety annotations during migration, so it's running the exact same code and the _only_ difference is the sdk upgrade to 2.12.0. It's the strangest thing!

Here's my code:

```dart

Future<void> sendEmail(String subjectText, String messageText) async {
  var mailgunServer = mailgun(
      'postmaster@sandbox_____.mailgun.org',
      '____');

  var message = Message()
    ..from = Address('___@gmail.com', '___')
    ..recipients.add(
        '___@gmail.com') 
    ..subject = subjectText
    ..text = messageText;

  var sendFuture = send(message, mailgunServer)
      .then((_) => print('email sent!'))
      .catchError((e) => print('Error: $e'));

  return sendFuture;
}

```

Here's the log when it works on sdk 2.10.0:

```console
FINER: 2021-03-19 16:33:19.258843: Connecting to smtp.mailgun.org at port 587.
FINE: 2021-03-19 16:33:19.352492: >
FINE: 2021-03-19 16:33:19.378829: < 220 Mailgun Influx ready
FINE: 2021-03-19 16:33:19.382727: > EHLO ________
FINE: 2021-03-19 16:33:19.412950: < 250 smtp-out-n07.prod.us-west-2.postgun.com
< 250 AUTH PLAIN LOGIN
< 250 SIZE 52428800
< 250 8BITMIME
< 250 SMTPUTF8
< 250 PIPELINING
< 250 STARTTLS
FINE: 2021-03-19 16:33:19.414913: > STARTTLS
FINE: 2021-03-19 16:33:19.452953: < 220 Go ahead
FINE: 2021-03-19 16:33:19.541710: > EHLO __________
FINE: 2021-03-19 16:33:19.570976: < 250 smtp-out-n07.prod.us-west-2.postgun.com
< 250 AUTH PLAIN LOGIN
< 250 SIZE 52428800
< 250 8BITMIME
< 250 SMTPUTF8
< 250 PIPELINING
FINE: 2021-03-19 16:33:19.572924: > AUTH LOGIN
FINE: 2021-03-19 16:33:19.600218: < 334 ____________
FINE: 2021-03-19 16:33:19.603157: > _________________
FINE: 2021-03-19 16:33:19.629493: < _______________
FINE: 2021-03-19 16:33:19.633381: > _________________
FINE: 2021-03-19 16:33:19.680206: < 235 Authentication successful
FINE: 2021-03-19 16:33:19.682163: > MAIL FROM:<_____________@gmail.com> SMTPUTF8
FINE: 2021-03-19 16:33:19.707519: < 250 Sender address accepted
FINE: 2021-03-19 16:33:19.709459: > RCPT TO:<_______________@gmail.com>
FINE: 2021-03-19 16:33:19.733843: < 250 Recipient address accepted
FINE: 2021-03-19 16:33:19.734818: > DATA
FINE: 2021-03-19 16:33:20.031346: < 354 Continue
FINE: 2021-03-19 16:33:20.059614: > .
FINE: 2021-03-19 16:33:20.159115: < 250 Great success
FINE: 2021-03-19 16:33:20.160075: > QUIT
email sent!

```

And here's the log when it fails on sdk 2.12.0:

```console
FINER: 2021-03-19 16:34:38.333559: Connecting to smtp.mailgun.org at port 587.
FINE: 2021-03-19 16:34:38.424279: >
FINE: 2021-03-19 16:34:38.451590: < 220 Mailgun Influx ready
FINE: 2021-03-19 16:34:38.455478: > EHLO ____________
FINE: 2021-03-19 16:34:38.485716: < 250 smtp-out-n01.prod.us-west-2.postgun.com
< 250 AUTH PLAIN LOGIN
< 250 SIZE 52428800
< 250 8BITMIME
< 250 SMTPUTF8
< 250 PIPELINING
< 250 STARTTLS
FINE: 2021-03-19 16:34:38.487679: > STARTTLS
FINE: 2021-03-19 16:34:38.521804: < 220 Go ahead
FINE: 2021-03-19 16:34:38.618377: > EHLO ______________
FINE: 2021-03-19 16:34:38.649594: < 250 smtp-out-n01.prod.us-west-2.postgun.com
< 250 AUTH PLAIN LOGIN
< 250 SIZE 52428800
< 250 8BITMIME
< 250 SMTPUTF8
< 250 PIPELINING
FINE: 2021-03-19 16:34:38.652501: > AUTH LOGIN
FINE: 2021-03-19 16:34:38.680788: < 334 ______________
FINE: 2021-03-19 16:34:38.686652: > _______________________
FINE: 2021-03-19 16:34:38.714925: < 334 _________________
FINE: 2021-03-19 16:34:38.717850: > _____________________
FINE: 2021-03-19 16:34:38.745160: < 235 Authentication successful
FINE: 2021-03-19 16:34:38.751988: > MAIL FROM:<______________@gmail.com> SMTPUTF8
FINE: 2021-03-19 16:34:38.776373: < 250 Sender address accepted
FINE: 2021-03-19 16:34:38.787101: > RCPT TO:<___________@gmail.com>
FINE: 2021-03-19 16:34:38.813436: < 250 Recipient address accepted
FINE: 2021-03-19 16:34:38.819289: > DATA
FINE: 2021-03-19 16:34:38.847586: < 354 Continue
FINE: 2021-03-19 16:34:38.859278: > .
WARNING: 2021-03-19 16:34:38.863179: Could not send mail.
Error: Socket was closed even though a response was expected.

```

**Comment by close2** [comment]
@OlegAlexander I've opened a new issue.
Does this problem still exist?

**Comment by brunodmn** [comment]
I am still having this problem, just tried with latest version of mailer.
I am using:
```
 final smtpServer = gmailRelaySaslXoauth2(
         '${smtp.username}', 
         '${smtp.oauth2}');
```

If you need further information ask for it and I'd reply, or you can just try to execute the code above with your credentials.

Detail, I have 2 factor authentication on this smtp gmail account.

**Comment by OlegAlexander** [comment]
@close2, mailer 5.0.0 resolved the issue for me. But I'm not using two-factor authentication.

**Comment by jaczura1977** [comment]
I am using mailer 5.0.2 and have the same issue.
final smtpServer = gmailRelaySaslXoauth2(email, accessToken!);

The accessToken starts with ya29. so it is valid, the login sucess.

**Comment by close2** [comment]
@jaczura1977 could you please enable debugging (see previous comments) and reopen this issue.
