### ISSUE TITLE
compile error after upgrading to latest mailer version

### ISSUE THREAD

**Issue by AlanSGC** [kaisellgren/mailer#107]
I resumed an app that was stopped for a few months and now no longer works. The app worked perfectly with version 1.2.3 of the mailer plugin. When upgrading to newer versions (3.0.1), I can no longer compile the app. Below is the description of the error ...

Compiler message:
file:///Users/alan_costa/Downloads/flutter/.pub-cache/hosted/pub.dartlang.org/mailer-3.0.1/lib/src/smtp/connection.dart:151:32: Error: The argument type 'Utf8Decoder' can't be assigned to the parameter type 'StreamTransformer<Uint8List, dynamic>'.
 - 'Utf8Decoder' is from 'dart:convert'.
 - 'StreamTransformer' is from 'dart:async'.
 - 'Uint8List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'StreamTransformer<Uint8List, dynamic>'.
        _socket.transform(utf8.decoder).transform(const LineSplitter()));

My pubspec.yaml file:
...
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.2
  flutter_masked_text: ^0.8.0
  sqflite: ^1.1.5
  path_provider: ^1.1.0
  intl: ^0.15.8
  firebase_auth: ^0.11.1+5
  firebase_messaging: ^5.0.2
  firebase_analytics: ^3.0.2
  cloud_firestore: ^0.12.2
  firebase_storage: ^3.0.1
  transparent_image: ^1.0.0
  package_info: ^0.4.0+4
  url_launcher: ^5.0.3
  material_design_icons_flutter: ^3.2.3695
  image_picker: ^0.6.0+9
  mailer: 3.0.1
  connectivity: ^0.4.3+6
  diacritic: ^0.1.1
  http: ^0.12.0+2
  location: ^2.3.5
  geolocator: ^5.0.1

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.2-pre.189, on Mac OS X 10.14.5 18F132, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

Any suggestions to solve this problem?

Thank you

**Comment by close2** [comment]
I have implemented to proposed fixes from:
https://groups.google.com/forum/#!topic/flutter-announce/LTe4SYU8-0Q

I don't have flutter installed currently. **Please report back if version 3.0.2 fixes your problems.**

**Comment by close2** [comment]
Please reopen if the problem still exists.
