### ISSUE TITLE
sendReports.forEach((sr)  is not working

### ISSUE THREAD

**Issue by NTMS2017** [kaisellgren/mailer#110]
I upgrade the mailer plugin from mailer: ^2.5.0 to mailer: ^3.0.2 and it seems sendReports.forEach changed. how should I use sendReports.forEach((sr) for upgrade version?

```
final sendReports = await send(message, smtpServer);
    sendReports.forEach((sr) {
      if (sr.sent) {
        setState(() {
```

**Comment by close2** [comment]
version 3 changed the return type from `List<SendReport>` to `SendReport`

```dart
final sendReport = await send(message, smtpServer);
   if (sendReport.sent) {
        setState(() {
```
