### ISSUE TITLE
gmail blocked by Google

### ISSUE THREAD

**Issue by NTMS2017** [kaisellgren/mailer#111]
With new version (3.0.2) I try to use simple gmail option and it seems google blocked my mail.
Any idea how to securely use gmail to send mail in my Flutter app?

**Comment by close2** [comment]
I've written an example using XOAUTH2:
https://github.com/kaisellgren/mailer/tree/master/example/gmail_xoauth2

Unless you are working on a private project I would recommend against using google for mail sending.  The token / password will always allow reading mails as well.

You can easily create accounts at companies like socketlabs (if you are a business) which are specialized in sending mails.
