### ISSUE TITLE
not working in flutter

### ISSUE THREAD

**Issue by avdisx** [kaisellgren/mailer#116]
hi my friend. flutter mailer3.0.2 is not working. i cant understand u.

**Comment by avdisx** [comment]
I created a button in the project and I wrote the code in the example given by your plugin in the method. app code is;
`


> I need more infos.
> Does it compile?
> What happens?
> Is there a log output?
> Try enabling log output:
> 
> ```dart
>     Logger.root.level = Level.ALL;
>     Logger.root.onRecord.listen((LogRecord rec) {
>       print('${rec.level.name}: ${rec.time}: ${rec.message}');
>     });
> ```
```import 'package:flutter/material.dart';
import 'package:mailer/mailer.dart';
import 'package:mailer/smtp_server.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: RaisedButton(onPressed: (){sendMail();},child: Text("Mail Gönder"),),
      ),
    );
  }

  void sendMail() async {
    String username = 'mygmailadress';
    String password = 'mygmailpassword';

    final smtpServer = gmail(username, password);
    // Use the SmtpServer class to configure an SMTP server:
    // final smtpServer = SmtpServer('smtp.domain.com');
    // See the named arguments of SmtpServer for further configuration
    // options.

    // Create our message.
    final message = Message()
      ..from = Address(username, 'Your name')
      ..recipients.add('destination@example.com')
      ..ccRecipients.addAll(['destCc1@example.com', 'destCc2@example.com'])
      ..bccRecipients.add(Address('bccAddress@example.com'))
      ..subject = 'Test Dart Mailer library :: 😀 :: ${DateTime.now()}'
      ..text = 'This is the plain text.\nThis is line 2 of the text part.'
      ..html = "<h1>Test</h1>\n<p>Hey! Here's some HTML content</p>";

    try {
      final sendReport = await send(message, smtpServer);
      print('Message sent: ' + sendReport.toString());
    } on MailerException catch (e) {
      print('Message not sent.');
      for (var p in e.problems) {
        
        print('Problem: ${p.code}: ${p.msg}');
      }
    }
  }
}
`

screen is just message not send. I finished my project and only the e-mail section remained. Thank you for your interest.

**Comment by close2** [comment]
Please add
```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```
at the start of your `sendMail` function.

I am pretty sure that google is not allowing you to send mails.
Google does not make it easy to send mails using a username and password.
See https://github.com/kaisellgren/mailer/tree/master/example/gmail_xoauth2

**Comment by avdisx** [comment]
> Please add
> 
> ```dart
>     Logger.root.level = Level.ALL;
>     Logger.root.onRecord.listen((LogRecord rec) {
>       print('${rec.level.name}: ${rec.time}: ${rec.message}');
>     });
> ```
> 
> at the start of your `sendMail` function.
> 
> I am pretty sure that google is not allowing you to send mails.
> Google does not make it easy to send mails using a username and password.
> See https://github.com/kaisellgren/mailer/tree/master/example/gmail_xoauth2

what should I import for Logger?

**Comment by avdisx** [comment]
> Please add
> 
> ```dart
>     Logger.root.level = Level.ALL;
>     Logger.root.onRecord.listen((LogRecord rec) {
>       print('${rec.level.name}: ${rec.time}: ${rec.message}');
>     });
> ```
> 
> at the start of your `sendMail` function.
> 
> I am pretty sure that google is not allowing you to send mails.
> Google does not make it easy to send mails using a username and password.
> See https://github.com/kaisellgren/mailer/tree/master/example/gmail_xoauth2

its Work. Thanks everything

my full code.
`import 'package:logging/logging.dart';
import 'package:mailer/mailer.dart';
import 'package:flutter/material.dart';
import 'package:mailer/smtp_server.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: RaisedButton(
          onPressed: () {
            sendMail();
          },
          child: Text("Mail Gönder"),
        ),
      ),
    );
  }

  void sendMail() async {
    String _username = 'mycompanyadress@company.net';
    String _password = 'mailpassword';
 String _mailGidecekAdres = "sendingmailadress";
    final smtpServer = new SmtpServer('smtp.avseng.net',
        username: _username,
        password: _password,
        ignoreBadCertificate: false,
        ssl: false,
        allowInsecure: true);

    String mesajIcerigi = "messagetext";
    String konu = "Message subject";
   

    // Create our message.
    final message = Message()
      ..from = Address("$_username", 'name')
      ..recipients.add('$_mailGidecekAdres')
      ..subject = konu
      ..text = mesajIcerigi;

    try {
      final sendReport = await send(message, smtpServer);
      print('Message sent: ' + sendReport.toString());
    } on MailerException catch (e) {
      print('Message not sent.');

      for (var p in e.problems) {
        print('Problem: ${p.code}: ${p.msg}');
      }
    }
  }
}
`

> thanks again.
Flutter is best :)
