### ISSUE TITLE
SmtpClientAuthenticationException (Incorrect username / password / credentials)

### ISSUE THREAD

**Issue by eatteer** [kaisellgren/mailer#117]
Hi
I want to handle the app always with only two emails, for example: from: "myflutter@gmail.com" and recipient: "usupport@gmail.com"

Thank you in advance

![code](https://user-images.githubusercontent.com/55556476/65927058-cf6f1b00-e3bd-11e9-9497-bd9884f955a7.PNG)
![error2](https://user-images.githubusercontent.com/55556476/65927064-d39b3880-e3bd-11e9-8b20-c458a5be2b3c.PNG)

**Comment by close2** [comment]
You should probably find an smtp-service, which can restrict the destination addresses.

If you want to use gmail, you'll need to use xoauth2:
https://github.com/kaisellgren/mailer/tree/master/example/gmail_xoauth2

It is not very difficult to extract your credentials from flutter apps, and use them to send spam!
