### ISSUE TITLE
RangeError for certain email subjects

### ISSUE THREAD

**Issue by pjkroll** [kaisellgren/mailer#118]
**How to reproduce the error**
Create message with subject: '[Sime of some] Artur Maggelwegri [Dakończone]'

**Exception**
`Unhandled exception:
RangeError (index): Index out of range: index should be less than 46: 46
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      split (package:mailer/src/smtp/internal_representation/conversion.dart:34:74)
#2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
#3      _IRHeader._outValueB64 (package:mailer/src/smtp/internal_representation/ir_header.dart:30:19)
<asynchronous suspension>
#4      _IRHeaderText.out (package:mailer/src/smtp/internal_representation/ir_header.dart:59:14)
#5      _IRContent._outH.<anonymous closure> (package:mailer/src/smtp/internal_representation/ir_content.dart:20:41)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#7      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#8      _IRContent._outH (package:mailer/src/smtp/internal_representation/ir_content.dart:20:28)
<asynchronous suspension>
#9      _IRContent._out64 (package:mailer/src/smtp/internal_representation/ir_content.dart:27:12)
<asynchronous suspension>
#10     _IRContentText.out (package:mailer/src/smtp/internal_representation/ir_content.dart:195:12)
#11     _IRContentPart.out (package:mailer/src/smtp/internal_representation/ir_content.dart:63:29)
<asynchronous suspension>
#12     _IRContentPart.out (package:mailer/src/smtp/internal_representation/ir_content.dart:63:29)
<asynchronous suspension>
#13     IRMessage.data (package:mailer/src/smtp/internal_representation/ir_message.dart:31:16)
#14     sendSingleMessage (package:mailer/src/smtp/smtp_client.dart:187:32)
<asynchronous suspension>
#15     _send (package:mailer/src/smtp/mail_sender.dart:133:11)
<asynchronous suspension>
#16     send (package:mailer/src/smtp/mail_sender.dart:94:26)
<asynchronous suspension>
#17     main (file:///home/someone/dev/flutter/mailer_test/bin/main.dart:32:9)
<asynchronous suspension>
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)`

**Comment by close2** [comment]
thanks for reporting

**Comment by pjkroll** [comment]
Thank you for fast reaction and for the library.
