### ISSUE TITLE
Gmail SMTP Server raises either incorrect credentials or HandshakeException

### ISSUE THREAD

**Issue by rroger** [kaisellgren/mailer#123]
Hello there, 
when I try to send an email via gmail with ssl = true or another smtp client with ssl I'll get this error:
HandshakeException: Handshake e (OS Error: WRONG_VERSION_NUMBER.cc:242)

I try to run it on iOS13.2 (I first thought it could be connected with https://discussions.apple.com/thread/250682648 ) but I'm not sure anymore, because the problem remains event with iOS13.2.

Any ideas what the problem could be? 

 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (3 available)

• No issues found!

**Comment by rroger** [comment]
[Update] The problem arises only with ssl: true. not sure if thats how it is meant to be for some reason, but without ssl: true and some modification in the gmail setting (https://support.google.com/a/answer/6260879?hl=de) it worked. I needed to allow access for less secure apps to send mails from my flutter test app.

**Comment by close2** [comment]
There is already a gmail server configuration, which correctly sets ssl, port, tls,...

SMTP usually does not use SSL but TLS.  The client connects on an unencrypted port and asks the server to switch to encryption (using STARTTLS).  This means that your connection is usually still encrypted.

You can prevent "using less secure apps" by following:
https://github.com/kaisellgren/mailer/tree/master/example/gmail_xoauth2

**Comment by rroger** [comment]
Thanks a lot for your reply! I will look into the gmail_xoauth2
