### ISSUE TITLE
Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8. 

### ISSUE THREAD

**Issue by jzz567** [kaisellgren/mailer#128]
Dart:2.7.0
Mailer:3.0.4
When I call `send`,it always return this error:
`Dart_NewStringFromUTF8 expects argument 'str' to be valid UTF-8.`
Is this a dart VM bug?

**Comment by close2** [comment]
It's highly unlikely that this is a dart VM bug.

Please enable debugging output:
```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```

You probably read bytes from the filesystem (mail addresses,..) and use an incorrect encoding.
