### ISSUE TITLE
[Feature] - Receiving emails

### ISSUE THREAD

**Issue by TomTruyen** [kaisellgren/mailer#129]
I like the current package though maybe it will be an idea to expand it so that people can also get their Inbox? To make an actual email app for example. I will try it myself but I don't think I'm skilled enough yet. Maybe if someone has time they can implement this feature?

Thanks

**Comment by close2** [comment]
there is already an imap library:
https://pub.dev/packages/imap_client

There's nothing wrong in using 2 libraries for receiving and sending mails.

Obviously the entities representing mails are different.  I am open to changing my representation / adding a 2nd representation if you can demonstrate that this would simplify writing a mail client.

I haven't looked at imap_client yet, if the representations are similar we could possibly depend on another (new) email-entity-library.

**Comment by TomTruyen** [comment]
True but biggest problem with imap_client is that Gmail automatically blocks any login/authentication request of imap_client

**Comment by close2** [comment]
It's probably enough to implement oauth in the imap_client library:
https://developers.google.com/gmail/imap/xoauth2-protocol

I've only recently added this in mailer.

If you really would like to get your hands dirty, ask the imap_client maintainer if s/he would consider accepting a Pull-Request for this feature.  The communication with the server is pretty simple.

Getting the token,... is the hard(er) part, but that should be exactly the same as getting the token for smtp (i.e. this library)

**Comment by TomTruyen** [comment]
Thanks for all this information and fast response. I’ll see what I can make of it now as I didn’t even know oauth could fix the issue

Sent from Mail for Windows 10
