### ISSUE TITLE
how to send email via sendgrid using this package

### ISSUE THREAD

**Issue by jain-shreyansh** [kaisellgren/mailer#130]
need code snippet for using sendgrid with this package

**Comment by close2** [comment]
Try:

`final smtpServer = SmtpServer('smtp.sendgrid.net');`
smtp server location from: https://sendgrid.com/solutions/smtp-service/

Please create a PR in case it works.  (See https://github.com/kaisellgren/mailer#smtp-definitions)

**Comment by sgehrman** [comment]
where do you set the api key?

**Comment by vanlooverenkoen** [comment]
When 2fa is enabled you should use this.
```final smtpServer = sendgrid('apikey', 'your-actual-api-key');```
