### ISSUE TITLE
Gmail: Image not display

### ISSUE THREAD

**Issue by GaetanFauconnier85** [kaisellgren/mailer#133]
I want to write an email with a image.
The email is send but when i open it the image is blanck.
Did i mis something ? And other question, how can i attache image ?
Thanks 
Best regards

`      
```
Uint8List qr = await _generateBarCode(element.idDiscount);
      print(qr);
      var image = BASE64.base64Encode(qr);
      print(image);
```

    final smtpServer = gmail('**','**);
    print(emailUser);
    final message = Message()
    ..from = Address('***')
    ..recipients.add(emailUser) //recipent email
    ..subject = "oui"
    ..html = "<div> <p>Taken from wikpedia</p> <img src=\"data:image/png;base64, $image\" alt=\"Logo\" title=\"Logo\" style=\"display:block\" width=\"200\" height=\"87\" />";

    try {
    final sendReport = await send(message, smtpServer);
    print('Message sent: ' +
    sendReport.toString()); //print if the email is sent
    } on MailerException catch (e) {
    print('Message not sent. \n' +
    e.toString()); //print if the email is not sent
    // e.toString() will show why the email is not sending
    }`

![image](https://user-images.githubusercontent.com/36500464/73390211-f2f79300-42d5-11ea-83ba-2012f1e51c5a.png)

**Comment by close2** [comment]
Please send me this email: christian@loitsch.com
I'll take a look.

Have you seen
https://github.com/kaisellgren/mailer/issues/85 and
https://github.com/kaisellgren/mailer/issues/104
?

**Comment by GaetanFauconnier85** [comment]
Hi,The probleme seems come from gmail and not the mail because when i try to transfer the email to you, the picture apears well.So hi send my picture in attachement and its work pretty well.Thanks for you help,Best Regards Provenance : Courrier pour Windows 10 De : Christian LoitschEnvoyé le :jeudi 30 janvier 2020 09:35À : kaisellgren/mailerCc : GaetanFauconnier85; AuthorObjet :Re: [kaisellgren/mailer] Gmail: Image not display (#133) Please send me this email: christian@loitsch.comI'll take a look.Have you seen#85 and#104?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by close2** [comment]
If I understand correctly your images are in base64.
A lot of mail programs don't display them.

Try inline attachments.

I've used this:
`<img alt="Bewerbung" height="auto" src="cid:bewerbung.png@3.141" style="border:none;display:block;outline:none;text-decoration:none;height:auto;width:100%;" width="100">`
in one of my mails.
(I've created the mail using mjml, which I highly recommend: https://mjml.io/try-it-live)

The image was then added (in dart) like this:
`FileAttachment(File(a))
          ..location = Location.inline
          ..cid = "<bewerbung@3.141>")`

Note that the cid in the code has additional `<` and `>`

I can send you more details if you want (just send me an email).

**Comment by GaetanFauconnier85** [comment]
Thanks you for your kick answer ! Indeed my images was in base64Thanks again for the tips ! Provenance : Courrier pour Windows 10 De : Christian LoitschEnvoyé le :jeudi 30 janvier 2020 19:43À : kaisellgren/mailerCc : GaetanFauconnier85; AuthorObjet :Re: [kaisellgren/mailer] Gmail: Image not display (#133) If I understand correctly your images are in base64.A lot of mail programs don't display them.Try inline attachments.I've used this:<img alt="Bewerbung" height="auto" src="cid:bewerbung.png@3.141" style="border:none;display:block;outline:none;text-decoration:none;height:auto;width:100%;" width="100">in one of my mails.(I've created the mail using mjml, which I highly recommend: https://mjml.io/try-it-live)The image was then added (in dart) like this:FileAttachment(File(a)) ..location = Location.inline ..cid = "<bewerbung@3.141>")Note that the cid in the code has additional < and >I can send you more details if you want (just send me an email).—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Harshana-Rathnayaka** [comment]
> If I understand correctly your images are in base64.
> A lot of mail programs don't display them.
> 
> Try inline attachments.
> 
> I've used this:
> `<img alt="Bewerbung" height="auto" src="cid:bewerbung.png@3.141" style="border:none;display:block;outline:none;text-decoration:none;height:auto;width:100%;" width="100">`
> in one of my mails.
> (I've created the mail using mjml, which I highly recommend: https://mjml.io/try-it-live)
> 
> The image was then added (in dart) like this:
> `FileAttachment(File(a)) ..location = Location.inline ..cid = "<bewerbung@3.141>")`
> 
> Note that the cid in the code has additional `<` and `>`
> 
> I can send you more details if you want (just send me an email).

Hey, I'm facing the same issue. My image is base64 and it's not displayed in the email. Also I checked inspect element. And there was no src property. I don't understand why. 

Also in your code 
`FileAttachment(File(a))` 

Where do you declare this variable `a` and how do you declare it? As a `File` ? If it's a `File` how do you assign the image to it? Sorry I'm a newbie!
