### ISSUE TITLE
Error when using with mailhog

### ISSUE THREAD

**Issue by e-belair** [kaisellgren/mailer#135]
Hi, I try to use mailer with Mailhog. But I'm getting this error:
```
HandshakeException: Handshake error in client (OS Error: WRONG_VERSION_NUMBER(tls_record.cc:242))
```
Here is my config (env file) that is applied to the SmtpServer() instance when I'm sending a mail:
```
# MAILHOG
MAIL_DRIVER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=1027
MAIL_SSL=true
MAIL_IGNORE_BAD_CERT=false
MAIL_ALLOW_INSECURE=false
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_FROM_ADDRESS=no-reply@my-site.fr
MAIL_FROM_NAME=Me
```

The mailhog server is mailhog:latest docker image

When I disable the SSL, the message is successfully sent but showed encrypted on mailhog.

**Comment by close2** [comment]
There are 2 ways to send mails over an encrypted connection:
SSL and START TLS

Start tls is far more common then SSL.

I guess mailhog is configured for start tls but not ssl.

Please enable debug output:
```
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```

and post the relevant lines.

Please reopen, if you think there's a bug in this library.

**Comment by e-belair** [comment]
Here is the log:
FINER: 2020-03-12 16:56:45.474174: Connecting to 127.0.0.1 at port 1027.

**Comment by close2** [comment]
This indicates that mailer can't connect.

Please try to connect to mailhog using either telnet or openssl.
If ssl is really enabled, then telnet should not work:
telnet 127.0.0.1 1027

If ssl is enabled, then openssl should work:
openssl s_client -connect 127.0.0.1:1027

In both cases mailhog should give a response when writing 'HELO xxx'.
