### ISSUE TITLE
Flutter Web

### ISSUE THREAD

**Issue by ShreeBhagwat** [kaisellgren/mailer#136]
Iam new to flutter,
How to this in flutter Web

**Comment by close2** [comment]
Please see https://flutter.dev/ and https://github.com/kaisellgren/mailer/tree/master/example

You probably shouldn't use this library in flutter, unless you ask the user for their username and password!

It is very easy to extract credentials from android apps.

**Comment by ShreeBhagwat** [comment]
So what I want to do is, I have and Enquiry form on my web page, where the user fills it’s name, and email address. 
Once he hits submit button I want to send him an email on the email address he has mentioned. 
I have my own business mail Id and I did all the SMTP setting in my mailer function . 
Iam not able to send mail through the website. 

I followed the example it’s has google SMTP settings , I also used my google mail id, it’s still not working

**Comment by close2** [comment]
Sorry.  I didn't read your original question correctly.

It is technically impossible to send mails with flutter Web.

You will need to either use a rest API or run a small service on a server.
Note that everybody can extract your username / password from flutter apps.  I highly recommend a small service on a server.

A lot of smtp providers also provide a rest api:
For instance https://www.socketlabs.com/api/

**Comment by ShreeBhagwat** [comment]
Hello
Sorry I know this must no go here
But I used socketlab api and everything is working fine
The problem is I get CORS error I tired all that I could from setting the
headers, to allowing the origin. When I disable the web security in chrome
it works fine and I can send message. Can you help me ?
I have almost spent entire day trying all the possible threads and outcome
. I use firebase as hosting and I also tried adding the headers into the
firebase.json file.

**Comment by close2** [comment]
https://www.socketlabs.com/blog/keeping-your-api-keys-secure-in-browser-applications/

socketlabs doesn't allow requests from a browser, as extracting your key is really easy.

I am sorry that I sent you on the wrong path.
If you use firebase there is another possibility:
https://firebase.google.com/products/extensions/firestore-send-email

**Comment by ShreeBhagwat** [comment]
Thank you for your response, Ill check about firebase extension. You have
really been a good help. Thank you again.
