### ISSUE TITLE
Sended email not showing in Sent folder of Sender

### ISSUE THREAD

**Issue by ali7234** [kaisellgren/mailer#138]
Email send successfully to recipients, but not shown in the sent folder of sender.

```
final message = Message()
      ..from = Address(from, 'Sender')
      ..recipients.add(Address(to, 'Recipient'))
      ..subject = subject
      ..text = composeEmail
      ..attachments = attachments;

try {
      final SendReport sendReport = await send(message, smtpServer);
      print('Message sent: ' + sendReport.toString());
    } on MailerException catch (e) {
      print('Message not sent. ${e.message}');
      for (var p in e.problems) {
        print('Problem: ${p.code}: ${p.msg}');
      }
    }
```

**Comment by Tienisto** [comment]
What was the fix?

**Comment by ali7234** [comment]
/// Send the MimeMessage through SMTP
      var sendResponse = await client.sendMessage(mimeMessage);

      /// Close the SMTP connection
      client.close();

      /// [if]: email send failed. Save in the Draft.
      /// [else]: append the message in the `INBOX.Sent`
      if (sendResponse.isFailedStatus) {
        _saveDraft();
      } else if (sendResponse.isOkStatus) {
        await S.sImapClient.appendMessage(mimeMessage, targetMailboxPath: "INBOX.Sent");
      }

**SMTP**  client just send the email to the recipients. I found the workaround for this problem is to append an email in **INBOX.Sent** folder as well.
