### ISSUE TITLE
mailer3 attachment doesn't worked as excepted

### ISSUE THREAD

**Issue by LeetaoGoooo** [kaisellgren/mailer#140]
```dart
    File file = new File(this.filePath);
    String fileName = basename(file.path);

    var message = new Message()
      ..from = Address(this.config.sendAccount, 'KindlePush(@author:Leetao)')
      ..recipients.add(this.sendTo)
      ..subject = fileName
      ..attachments.add(FileAttachment(file));
```
I tried use above code to send pdf or docx attachments,but not got as expected.

![image](https://user-images.githubusercontent.com/10162120/84665339-4d765080-af52-11ea-847f-382986fd5b68.png)

is there any wrong with my code?

**Comment by lt94** [comment]
I found that when the path containers special character like Chinese，the library works not well~

**Comment by close2** [comment]
I could not reproduce this bug.
Could you please give me a zip file with a complete example. (including an attachment which doesn't work)
