### ISSUE TITLE
HandshakeException  when sending a mail

### ISSUE THREAD

**Issue by Macacoazul01** [kaisellgren/mailer#146]
Everytime i try to send an email i'm getting this error:

```
import 'package:mailer/mailer.dart';
import 'package:mailer/smtp_server.dart';
final _smtpServer = gmail(_username, _password);

  final message = Message()
    ..from = Address(_username, 'Atendimento Cantina')
    ..recipients.add(mail)
    ..bccRecipients.add(Address(_receiverMail))
    ..subject = 'Test Dart Mailer library :: 😀 :: ${DateTime.now()}'
    ..text = 'This is the plain text.\nThis is line 2 of the text part.'
    ..html = "<h1>Test</h1>\n<p>Hey! Here's some HTML content</p>";

  try {
    final sendReport = await send(message, _smtpServer);
   print('Message sent: ' + sendReport.toString());
  } on MailerException catch (e) {
    print('Message not sent.');
    for (var p in e.problems) {
      print('Problem: ${p.code}: ${p.msg}');
    }
  }
```

Exception has occurred.
HandshakeException (HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:354)))

**Comment by close2** [comment]
Please enable logging output.
```dart

  if (args[verboseArg] as bool) {
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
  }
```

It seems that your OS uses a self signed certificate.  (Does your system intercept smtp / tls calls?)

If you need the library to ignore incorrect certificates, there is an option `ignoreBadCertificate`.
```dart
_smtpServer = gmail(...)
_smtpServer.ignoreBadCertificate = true;
```

DON'T SIMPLY IGNORE THIS WARNING.
Somebody, something is intercepting your connection to gmail and can retrieve passwords and mail content.

Please reopen you still think that this is a bug in mailer.
