### ISSUE TITLE
deprecated words

### ISSUE THREAD

**Issue by ifeoluwajoshua** [kaisellgren/mailer#149]
i git the error that gmail is depreacated

final SmtpServer smtpServer = gmail(username, password);

**Comment by close2** [comment]
`gmail` is deprecated use
`gmailSaslXoauth2`
or
`gmailRelaySaslXoauth2`

See https://github.com/kaisellgren/mailer/blob/master/lib/smtp_server/gmail.dart for more information.

**Comment by bhanuka96** [comment]
> `gmail` is deprecated use
> `gmailSaslXoauth2`
> or
> `gmailRelaySaslXoauth2`
> 
> See https://github.com/kaisellgren/mailer/blob/master/lib/smtp_server/gmail.dart for more information.

@close2 Thanks. How to find accessToken? I saw only client-id in my google console. is client-id my access-token?

**Comment by close2** [comment]
I hope this helps: https://github.com/kaisellgren/mailer/tree/master/example/gmail_xoauth2
