### ISSUE TITLE
package does not work on IOS

### ISSUE THREAD

**Issue by gizemgizg** [kaisellgren/mailer#150]
The package running on Android does not work on ios. I cannot send mail to the user.

**Comment by close2** [comment]
Please enable logging:

```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```

What exactly do you mean with:
«The package running on Android does not work on ios.»
Do you have a flutter app, which works on Android, but does not work on iOS?

**Comment by gizemgizg** [comment]
Mail does not go when my user signs up, although less secure apps are open. This situation does not apply to android. When the IOS user signs up, my gmail account shows "Login denied" and the mail does not go.

**Comment by close2** [comment]
I really need the debugging information.  (see my previous comment).

It sounds like google denies the login, which has nothing to do with the mailer lib.

You will probably always have problems trying to send mails using google (and hopefully other smtp-providers as well).

Google sees that different devices and IP addresses send mail with YOUR credentials.
They are stored in the app and everybody can extract them.

There are very few cases where using this library in flutter is a good idea.

Firebase is usually the way to go:
https://stackoverflow.com/questions/51055131/upload-form-to-firestore-with-flutter

**Comment by close2** [comment]
I need more information!

Please reopen if you still think, that there is a bug / problem in `mailer`
