### ISSUE TITLE
Example of form for mailing (iOS Android).

### ISSUE THREAD

**Issue by cryogeni** [kaisellgren/mailer#151]
I am looking for an example to make a form with the mailer plugin. And that the date be reused to add in the message to be sent later. Do you have this example?

**Comment by close2** [comment]
Please DO NOT use this library in your flutter app.

It is really easy to extract your credentials from a flutter app.
Everybody can extract them and then start sending spam, or reading your mails!

Use something like firebase instead:
https://stackoverflow.com/questions/51055131/upload-form-to-firestore-with-flutter
