### ISSUE TITLE
encoding name in Address

### ISSUE THREAD

**Issue by management-partners** [kaisellgren/mailer#152]
..from = Address(username, '注文')
When I send an email with the name above, there is a display error ????

**Comment by close2** [comment]
Could you please post the complete error message.

You can also enable logging to get better debugging information:
```dart
   Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```
