### ISSUE TITLE
Undefined name 'context'.

### ISSUE THREAD

**Issue by cryogeni** [kaisellgren/mailer#155]
I don't understand why I have this error here.

I'm trying to create a dialog to tell the user that the email has been sent successfully and another to say that it is refused.

```
> try {
      final sendReport = await send(message, smtpServer);
      print('Message envoyé: ' + sendReport.toString());
       showDialog(
      context: context,
      barrierDismissible: false,
      builder: (BuildContext context) {
        return new AlertDialog(
          title: new Text("Success"),
          content: new Text("Your order has been placed"),
          actions: <Widget>[
            new MaterialButton(
              onPressed: () {},
              child: new Text("close"),
            )
          ],
        );
      });
```

      
Error
Undefined name 'context'.
Try correcting the name to one that is defined, or defining the name.

**Comment by bdlukaa** [comment]
You're referecing a `context` (BuildContext) that doesn't exist.

**Comment by cryogeni** [comment]
here is the solution that works for me

https://pub.dev/packages/fluttertoast

`try {
      final sendReport2 = await send(message, smtpServer);
      print('Message envoyé: ' + sendReport2.toString());
      Fluttertoast.showToast(
          msg: "\u{2714} Demande envoyé avec succes",
          toastLength: Toast.LENGTH_SHORT,
          gravity: ToastGravity.BOTTOM,
          timeInSecForIosWeb: 1,
          backgroundColor: Colors.green,
          textColor: Colors.white,
          fontSize: 16.0);
    } on MailerException catch (e) {
      print('cMessage envoyé.');
      for (var p in e.problems) {
        Fluttertoast.showToast(
            msg: "\u{274c} Erreur",
            toastLength: Toast.LENGTH_SHORT,
            gravity: ToastGravity.CENTER,
            timeInSecForIosWeb: 1,
            backgroundColor: Colors.red,
            textColor: Colors.white,
            fontSize: 16.0);

        print('Probleme: ${p.code}: ${p.msg}');
      }
    }
  }
}`
