### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by bdlukaa** [kaisellgren/mailer#156]
Currently Flutter Feb neither Dart Web (dart2js) is not supported because the packages imports `dart:io`, which is not supported. That would be awesome if it could be supported somehow. I think the best way to implement it is through [Federated Plugins](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#federated-plugins)

**Comment by close2** [comment]
I don't think that this is possible.
Web-applications have to use the http protocol.  `mailer` communicates using the smtp-protocol.
