### ISSUE TITLE
Mailer with Exchange

### ISSUE THREAD

**Issue by mado-bohsali** [kaisellgren/mailer#158]
Dear mailer team,

I want to use the mailer package for sending emails from an Outlook exchange account (@aub.edu.lb). How can I achieve that? AUB is the organization name. What should I need to setup this service ?

Thanks,
Mohamad El Bohsaly

**Comment by jordantsap** [comment]
Use this and adjust it to your details:
Future (or void type) _sendMail() async {
    // TODO: REMOVE CREDENTIALS BEFORE GITHUB UPLOAD
    String username = 'username@domain.com';
    String password = 'password';

    final smtpServer = SmtpServer('mailserver url here', username: username, password: password);
    ##  bellow comments explains it  
    // Use the SmtpServer class to configure an SMTP server:
    // final smtpServer = SmtpServer('email.server.com');
    // See the named arguments of SmtpServer for further configuration
    // options.

    // Create our message.
    final message = Message()
      ..from = Address(username)
      ..recipients.add(bookerEmailController.text)
      ..subject = 'New user from feelsafe application needs your approval!}'
      ..text = 'This is the plain text.\nThis is line 2 of the text part.'
      ..html =
          "Message sent at ${DateTime.now()} \n From ${userPhoneController.text}\n Location: __________";

    try {
      final sendReport = await send(message, smtpServer);
      print('Message sent: ' + sendReport.toString());
    } on MailerException catch (e) {
      print('Message not sent.');
      for (var p in e.problems) {
        print('Problem: ${p.code}: ${p.msg}');
      }
    }
  }

**Comment by mado-bohsali** [comment]
Dear team,

Wishing you well. Please note that I have been trying to send emails (using me216@aub.edu.lb <mailto:me216@aub.edu.lb>) using mailer and I have received the following error:

flutter: Message not sent.
After sending MAIL FROM:<me216@aub.edu.lb> SMTPUTF8, response did not start with any of: [2].
Response from server: < 530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [MR2P264CA0140.FRAP264.PROD.OUTLOOK.COM]
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: SocketException: OS Error: Connection reset by peer, errno = 54, address = outlook.office365.com, port = 58241

Please note that in my app, it will contain different emails of different domains to be sent from. What do you advise?

Sincerely,
Mohamad

**Comment by jordantsap** [comment]
Maybe you should restart or even stop, clean and invalidate caches.
Which flutter channel do you use?
Output the flutter doctor -v here please

**Comment by mado-bohsali** [comment]
Freelancer (https://www.freelancer.com/)

Mohamad has given you $20 USD to try Freelancer!

Freelancer.com gives you access to millions of freelancers from all around the world. Simply answer a few quick questions to post a project, and receive free quotes from freelancers in just a few minutes.

Claim Your $20 → (https://www.freelancer.com/get?id=43464147&source=gge)

* Credit available when you have verified your payment method.

What can you get done on Freelancer?

Graphic Design (https://www.freelancer.com/graphic-designers)
Website Development (https://www.freelancer.com/website-developers)
Translation (https://www.freelancer.com/translators)

Marketing (https://www.freelancer.com/internet-marketing)
Mobile Development (https://www.freelancer.com/mobile-app-development)
Photography (https://www.freelancer.com/local/photography)

© 2021 Freelancer Technology Pty Limited. All Rights Reserved.

Level 37, 225 George Street, Sydney, NSW 2000, Australia

Privacy Policy (https://www.freelancer.com/page.php?p=info%2Fprivacy)  |  Terms and Conditions (https://www.freelancer.com/page.php?p=info%2Fterms)  |  Unsubscribe (https://www.freelancer.com/users/email/subscriptions.php?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkZyZWVsYW5jZXJcXEdBRlxcQ29yZVxcSldUXFxKV1QifQ.eyJpZCI6bnVsbCwic3ViIjoidW5zdWJzY3JpYmUiLCJpYXQiOjE2MTEyNTAxMjl9._0tC40Fv4KHBYZeTZyAxVkmWC7gvbDpTpQSxWQicH0o)  |  Get Support (https://www.freelancer.com/support)  |  Get Free Credit (https://www.freelancer.com/give?from=email_footer)

Facebook (https://www.facebook.com/fansoffreelancer)

Twitter (https://twitter.com/freelancer)

Instagram (https://www.instagram.com/freelancerofficial)

Download our mobile app (https://bnc.lt/edm-download-freelancer)

(https://bnc.lt/edm-download-freelancer)

**Comment by close2** [comment]
it shouldn't be necessary to touch any caches,...

Create different smtpServer and use them accordingly:
```dart
final smtpServer1 = SmtpServer('mailserver1 url here', username: username, password: password);
final smtpServer2 = SmtpServer('mailserver2 url here', username: username, password: password);
```
...

**Comment by mado-bohsali** [comment]
Hi team,

I have gotten my SMPT server settings after signing into Outlook. However. I still receive the below error in Flutter

Client was not authenticated to send anonymous mail during MAIL FROM [MR2P264CA0191.FRAP264.PROD.OUTLOOK.COM]



Pleas advise.

Thanks,
Mohamad

**Comment by close2** [comment]
Does this help?
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_winother-mso_o365b/client-was-not-authenticated-to-send-anonymous/d405bcb0-f40c-42fa-b1b2-477597100123

**Comment by mado-bohsali** [comment]
Join Freelancer Today! | Freelancer

(https://www.freelancer.com/)

Mohamad has given you $20 in credit* to spend on our website.

Claim Your $20 Now → (https://www.freelancer.com/get?id=43464147&source=gge)

Freelancer.com gives you access to millions of freelancers, from all around the world.

If there's a task that you've been meaning to complete - whether it be for business or personal means - there's an expert out there who will get it done for you.

But the clock is ticking - you only have 48 hours left before we return the gift!

* Credit available when you have verified your payment method.

© 2021 Freelancer Technology Pty Limited. All Rights Reserved.
Level 37, 225 George Street, Sydney, NSW 2000, Australia

Privacy Policy (https://www.freelancer.com/about/privacy) | Terms and Conditions (https://www.freelancer.com/about/terms) | Unsubscribe (https://www.freelancer.com/emails/unsubscribe.php?s=UEhMYVRCT3hBNFlNZG9pY2d5Q3Z0cF82YjNmZEVqU045ckpIWGRFdnFONU5qelR5azBqZ3NnekxscUt5YTElMkZBbWZTRW1YJTJGY05sdlBqN2VEYk1ZYlNUdjlGRFByekVaa3Ewc0hXRGZ5VlBMJTJCU3owR1NCcnNHUzRzTiUyRjklMkZ5REFnaTZ2SHV4UTZhZnNVNGpwYUh1dW5EdWM=) | support@freelancer.com (mailto:support@freelancer.com)

Facebook (https://www.facebook.com/fansoffreelancer) Twitter (https://twitter.com/freelancer) Instagram (https://www.instagram.com/freelancerofficial)

Download our mobile app (https://bnc.lt/edm-download-freelancer)

(https://bnc.lt/edm-download-freelancer)
