### ISSUE TITLE
Mailer and Outlook Exchange

### ISSUE THREAD

**Issue by mado-bohsali** [kaisellgren/mailer#159]
Dear mailer team,

I want to use the mailer package for sending emails from an Outlook exchange account (@aub.edu.lb). How can I achieve that? AUB is the organization name. What should I need to setup this service ?

Thanks,
Mohamad El Bohsaly

**Comment by close2** [comment]
You will need the smtp server information for this account.
`mailer` only supports the smtp protocol.

**Comment by close2** [comment]
closing because of issue #158
