### ISSUE TITLE
Unhandled Exeption

### ISSUE THREAD

**Issue by prooshani** [kaisellgren/mailer#162]
Hey Everyone,
I am trying to use this package to send emails using my own smtp server (not gmail,yahoo, etc).
The app working well on a real device while throwing exceptions on iOS/Android Simulator/Emulator.

The error for both iOS and Android is same:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter ( 5322): 	WRONG_VERSION_NUMBER(tls_record.cc:242))

```
Note: smtpServer setup seems to be OK due to the fact that the app is able to send Email on a physical device without problem.

Any suggestion would highly appreciated.

Complete Output : 
`E/flutter ( 5322): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter ( 5322): 	WRONG_VERSION_NUMBER(tls_record.cc:242))
E/flutter ( 5322): #0      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:101:51)
E/flutter ( 5322): #1      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:815:22)
E/flutter ( 5322): #2      _RawSecureSocket._tryFilter.<anonymous closure> (dart:io/secure_socket.dart:936:13)
E/flutter ( 5322): #3      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 5322): #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 5322): #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
E/flutter ( 5322): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
E/flutter ( 5322): #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
E/flutter ( 5322): #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
E/flutter ( 5322): #9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
E/flutter ( 5322): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 5322): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 5322): #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 5322): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 5322): #14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 5322): #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)`

**Comment by close2** [comment]
I think this indicates that you try to connect to switch to a secure connection on an smtp server which doesn't support ist.

Are the SMTP settings really the same for your real device vs your app in the emulator?

**Comment by prooshani** [comment]
> I think this indicates that you try to connect to switch to a secure connection on an smtp server which doesn't support ist.
> 
> Are the SMTP settings really the same for your real device vs your app in the emulator?

Yes, I am running the app exactly at the same time on the emulator and real device.
It looks like Emulator/Simulator networking parts are working different compared to the real devices.

**Comment by close2** [comment]
I don't think that `mailer` is responsible for this error.
Please open a bug report with `flutter` (or try to find help on for example stackoverflow.

As I have no idea how to help you (and this is probably not something `mailer` is doing incorrectly) I'll close this issue.  
Please reopen if you still think that we have to do something in `mailer`.
