### ISSUE TITLE
How to recieve email with this package

### ISSUE THREAD

**Issue by nailuj29gaming** [kaisellgren/mailer#168]
How can I read emails using this package?

**Comment by masteradit** [comment]
Hey @nailuj29gaming! I think this package can only send emails.

The README.md file in this repo has this line:
> **mailer** is an easy to use library for composing and sending emails in Dart.

Try looking at other IMAP or POP3 related packages. I found [imap_client](https://pub.dev/packages/imap_client) and [enough_mail](https://pub.dev/packages/enough_mail) on pub.dev. I hope this helps.

**Comment by nailuj29gaming** [comment]
@masteradit do either of those libraries support google Oauth?

**Comment by masteradit** [comment]
@nailuj29gaming I am not sure about it. Check out their source code and/or issues.
