### ISSUE TITLE
Usage with web app

### ISSUE THREAD

**Issue by mat100payette** [kaisellgren/mailer#174]
Can this be used inside a web app if all `dart.io` imports are replaced with [universal_io](https://pub.dev/packages/universal_io) ?

I have to mail stuff from a button click on browser.

**Comment by close2** [comment]
No.  This is technically not possible.  A browser can not open a "plain" network connection.

Even if it was possible it would be a terrible idea, as everybody could extract username and password from your webapp and send spam with your credentials.
