### ISSUE TITLE
gmail() is deprecated and gmailSaslXoauth2() is always giving error.

### ISSUE THREAD

**Issue by aboli-waikar** [kaisellgren/mailer#175]
smtpServer function gmail() is deprecated. I tried using gmailSaslXoauth2() function. I am always getting below error. The functionality works if I use gmail(String userName, String password).

E/flutter (22498): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Socket was closed even though a response was expected.
E/flutter (22498): #0      Connection.send (package:mailer/src/smtp/connection.dart:82:9)
E/flutter (22498): <asynchronous suspension>
E/flutter (22498): 
E/flutter (22498): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Future<ServerResponse?>' is not a subtype of type 'FutureOr<ServerResponse>' in type cast
E/flutter (22498): #0      _doAuthXoauth2 (package:mailer/src/smtp/smtp_client.dart:94:7)
E/flutter (22498): #1      _doAuthentication (package:mailer/src/smtp/smtp_client.dart:104:21)
E/flutter (22498): #2      connect (package:mailer/src/smtp/smtp_client.dart:137:11)
E/flutter (22498): <asynchronous suspension>
E/flutter (22498): #3      send (package:mailer/src/smtp/mail_sender.dart:91:20)

**Comment by close2** [comment]
Please enable debugging:
```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
        print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```
Post the log messages here, but make sure to remove your credentials from the log output!
