### ISSUE TITLE
Usage with IOS

### ISSUE THREAD

**Issue by AlparslanBA** [kaisellgren/mailer#176]
Is there any possibility to use your guys plugin on the IOS side? 
I currently am able to use the plugin on the android side through flutter, is there any way that i can make use of flutter here to implement both for IOS and Android at the same time?

**Comment by close2** [comment]
`mailer` should work on every platform where flutter works (except web).

If not, it is a limitation of flutter.

Google for flutter ios to find tutorials,... on how to create such an app.
