### ISSUE TITLE
type 'Null' is not a subtype of type 'FutureOr<SendReport>'

### ISSUE THREAD

**Issue by sunlimiter** [kaisellgren/mailer#177]
` var connection = PersistentConnection(smtpServer);`
![image](https://user-images.githubusercontent.com/4102545/118481542-2ddd3e80-b746-11eb-8133-ac58646cf5fb.png)

![image](https://user-images.githubusercontent.com/4102545/118481369-fcfd0980-b745-11eb-8d16-ece22271e1f1.png)
![image](https://user-images.githubusercontent.com/4102545/118481385-04bcae00-b746-11eb-8692-153d1dd765c2.png)

**Comment by Mr-Lion** [comment]
![grafik](https://user-images.githubusercontent.com/6929357/124289235-c1ce6280-db5a-11eb-8676-ad3bce7a2cb5.png)


Hi, I have this problem here and can not use the mailer package. I urgently repair

**Comment by close2** [comment]
I think this is fixed with version 5.0.1

Please reopen if the problem still exists.
