### ISSUE TITLE
MailerException

### ISSUE THREAD

**Issue by sunilsharma2** [kaisellgren/mailer#179]
Gmail is deprecate, i have put less secure app so it works but after launching the app on app store and Google  playstore, many devices throws mailerException, please help

**Comment by close2** [comment]
Using your credentials in a flutter app is a really bad idea.
It's easy to extract them and then use your account to send spam mail.

Google probably detects that somebody else is using your credentials (which is correct) and blocks the callers.

Please don't use `mailer` in flutter apps with your credentials.

Take a look at firebase (and the trigger mail extension).
