### ISSUE TITLE
a Tag with href

### ISSUE THREAD

**Issue by mado-bohsali** [kaisellgren/mailer#190]
```dart
..html = '<p>Text</p> <a href=\"https://www.2suits.net/messages/?fepaction=messagebox\"></a>'
```

The link ain't appearing in the email body. Please advise.

**Comment by close2** [comment]
You should not escape the `"` (unless you're inside a `"` text.  Also there is no content inside the `a` attribute.

Try:
`..html = '<p>Text</p><a href="https://www.2suits.net/messages/?fepaction=messagebox">SOMETHING</a>`
