### ISSUE TITLE
Unhandled Exception: SocketException: OS Error: No route to host, errno = 113, address = smtp.gmail.com, port = 57668

### ISSUE THREAD

**Issue by amjad07** [kaisellgren/mailer#195]
Hi there,
I am experiencing this issue.
E/flutter (26224): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SocketException: OS Error: No route to host, errno = 113, address = smtp.gmail.com, port = 57668

I cross-checked the credentials and they are fine. ALso I tried with another gmail account has less secure apps feature enabled.

**Comment by close2** [comment]
Quite some ISPs block access to SMTP Servers on port 25.
It's possible that your ISP is overly cautious and blocks any connection to Googles smtp server.

This is mostly to prevent SPAM.
If this is the case there isn't much you can do.

A possible workaround would be https://pub.dev/packages/flutter_email_sender
Which is the correct way for sending mails in flutter.
