### ISSUE TITLE
Connection timed out, host: smtp.gmail.com, port: 587

### ISSUE THREAD

**Issue by DemitOfficial** [kaisellgren/mailer#196]
I am following documentation as it is. but I am getting this error.
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Connection timed out, host: smtp.gmail.com, port: 587
#0      _NativeSocket.connect.<anonymous closure>.<anonymous closure> (dart:io-patch/socket_patch.dart:920:11)
#1      _rootRun (dart:async/zone.dart:1420:47)
#2      _CustomZone.run (dart:async/zone.dart:1328:19)
#3      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:865:34)
#4      _rootRun (dart:async/zone.dart:1420:47)
#5      _CustomZone.run (dart:async/zone.dart:1328:19)
#6      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
#8      _rootRun (dart:async/zone.dart:1428:13)
#9      _CustomZone.run (dart:async/zone.dart:1328:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
#11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)

**Comment by close2** [comment]
Can you please verify, that you can connect to the smtp server using a different program.
It seems as if a firewall is blocking your connection.

On android try: https://k9mail.app/
and configure the outgoing smtp server with smtp.gmail.com / 587

On an iphone the native mail app should allow you to configure an outgoing server.

**Comment by close2** [comment]
can't reproduce
