### ISSUE TITLE
Explain why extracting credentials in Flutter is easy

### ISSUE THREAD

**Issue by luckyhandler** [kaisellgren/mailer#198]
The documentation states to "NOT use mailer together with your credentials" as "extracting them is very easy". 
It would be helpful to understand if this is about the general process of sending or if it is about decompiling an app and extracting the password.

Is it for example a suitable solution to extract the credentials to Firebase Remote Config and inject it during runtime?

**Comment by close2** [comment]
I was mostly thinking about decompiling.
I really don't know how firebase works.  Shouldn't it be possible to extract the firebase token from the app and then retrieve the config?

**Comment by close2** [comment]
--> don't use firebase to store credentials.

You can configure firebase to send emails directly.
(https://stackoverflow.com/questions/58934596/how-to-send-email-in-firebase-for-free)
