### ISSUE TITLE
Incorrect locale for date format in email header

### ISSUE THREAD

**Issue by michael-spf** [kaisellgren/mailer#201]
My use case:
I send emails from a Flutter app that are imported from another system via email fetching.
So far this has worked without any problems.

Now I want to update my app. Previously I updated Android Studio, Flutter, Dart and Flutter Packages.
Now the email fetching does not work anymore. After a very long search I have identified the problem.

Previously, the date in the header of the emails was sent by using english locale settings. Example:
date: **Sun, 16 Jan 2022 22:57:33 +0000**

Now, it is sent with my local locale (german). Example:
date: **So., 16 Jan. 2022 22:50:55 +0000**

Since I have tweaked the language settings in my app, I would imagine that this has now brought the bug to light.

Anyway, as far as I know, the date must always be specified with english locale settings.

I was able to fix the error for testing by modify that Cache File:
\Local\Pub\Cache\hosted\pub.dartlang.org\mailer-5.0.2\lib\src\smtp\internal_representation\ir_header.dart

At Lines #175/#176 I changed the following:
old: DateFormat('EEE, dd MMM yyyy HH:mm:ss +0000');
new: DateFormat('EEE, dd MMM yyyy HH:mm:ss +0000','en_US');

Is it possible to correct it here or anywhere, or is there another way to affect the date format in the header section?

Thanks in advance and best regards
Michael

**Comment by michael-spf** [comment]
I have tried many things and now I am quite sure that only the language and locale in the Android settings are decisive.

On a virtual device I have only English and Spanish installed, Spanish as the first language. In the app I have the language set to German. I only use the two digit language code. 

The date field in the email header was now sent in Spanish.

According to RFC5322 only English notation is allowed.

**Comment by close2** [comment]
Your fix is correct.

Please create a Pull Request.
