### ISSUE TITLE
Unable to Use after 30th May

### ISSUE THREAD

**Issue by heeshala** [kaisellgren/mailer#208]
From May 30th onwards  ​​Google will no longer support the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password

What will be the solution for using the package

**Comment by pasha13d** [comment]
Go to your email Setting. Then enable 2-step verification and later create App Password. Then Enable SMTP mail receiver option for your Gmail. Now in your app just use the newly generated Password with your gmail id.
