### ISSUE TITLE
unsupported_protocol(handshake_client.cc:697)

### ISSUE THREAD

**Issue by parmkub** [kaisellgren/mailer#209]
before upgrade flutter is version 3 . mailer error  UNSUPPORTED_PROTOCOL(handshake_client.cc:697)
#0           _SecureFilterImpl._handshake(dart:io-patch/secure_socket_patch.dart:99:46)  
#1           _SecureFilterImpl._handshake(dart:io-patch/secure_socket_patch.dart:99:46)  
#2           RawSecureSocket.secureHandshake(dart:io/secure_socket.dart:911:54)  
#3           RawSecureSocket._tryFilter(dart:io/secure_socket.dart:1040:19) 

How to fix it. thank

**Comment by close2** [comment]
This is not enough information.

Please enable debugging and provide the log output.
(Hide your password)

```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```
