### ISSUE TITLE
CC and BCC does not work

### ISSUE THREAD

**Issue by ThomasLocke** [kaisellgren/mailer#21]
I've tried the pub.dartlang.example, but I'm not getting any email to the CC and BCC recipients I'm adding.

I've tried using both Google SMTP and a local Postfix SMTP. I've tried a whole slew of different emailaddresses.

The To recipient get the email just fine. CC and BCC receives nothing.

Do I need to invoke some kind of special magic to make it work?  :o)

**Comment by ThomasLocke** [comment]
I see the problem. I'll whip up a patch soon (tm).  :)

**Comment by HoBi** [comment]
Any updates on this?

**Comment by link3988** [comment]
Hi BCC still does not work. Anyone have a fix?

**Comment by link3988** [comment]
BCC still doesn't work. Anyone have a fix?
