### ISSUE TITLE
how to get access token?

### ISSUE THREAD

**Issue by mayur-16** [kaisellgren/mailer#212]
I want to send email from my flutter windows app using gmail.

i tried to send mail using `final smtpServer= gmail(fromuser, password);`
but it showing me its depreciated..

now am trying using `smtpServer=gmailSaslXoauth2(fromuser, "access token");`

how to get access token for gmailSaslXoauth2 ? or is there any other method for sending mail?

**Comment by close2** [comment]
See the example in https://github.com/kaisellgren/mailer/tree/master/example/gmail_xoauth2

Much simpler: enable two-factor authentication and create an app password.
