### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 

### ISSUE THREAD

**Issue by cosmeaf** [kaisellgren/mailer#215]
E/flutter (11132): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (11132): 	WRONG_VERSION_NUMBER(tls_record.cc:242))
E/flutter (11132): #0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
E/flutter (11132): #1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
E/flutter (11132): #2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911:54)
E/flutter (11132): #3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040:19)
E/flutter (11132): <asynchronous suspension>
E/flutter (11132):

**Comment by close2** [comment]
This is not enough information to do anything.
