### ISSUE TITLE
Slow sending with 1Mb attachement

### ISSUE THREAD

**Issue by nico3587** [kaisellgren/mailer#220]
I try to send email with pdf file as attachement (size 1Mb) but it takes aprroximatively 2 minutes. Is it normal ?

**Comment by nico3587** [comment]
A litle precision, the problem is on Windows. I've just tried on Android and it's quick on this.

**Comment by close2** [comment]
How fast are other programs?
Please install for instance thunderbird and time sending 1MB.

If it is OS dependent the probability that there is something wrong in our code is low.

**Comment by nico3587** [comment]
You're right, I tried with Thunderbird and it's also slow. I tried on an other computer and it was fast. It was the computer I used the problem.

Thanks for your time.
