### ISSUE TITLE
View emails as sent in gmail

### ISSUE THREAD

**Issue by rodrigonepomuceno** [kaisellgren/mailer#221]
The submission process is working perfectly.
My question is if it would be possible for me to send an email using the tool and it would appear in my GMAIL sent items box.
I don't know if this is possible.

**Comment by close2** [comment]
Adding the mail to the sent folder is done over the IMAP protocol (which this library doesn't support).

You could try sending yourself the mail as BCC.  If I am not mistaken gmail will notice that the sending account equals the destination account and show your mail as sent mail.
