### ISSUE TITLE
Sending mail with Yahoo

### ISSUE THREAD

**Issue by 1Fenix** [kaisellgren/mailer#229]
Hi.

I would like to send mail using yahoo, but i don't seem to get it right. I tried following the instructions as given but I keep getting the "mail not sent" message. 
Could you please provide the yahoo.dart file as the gmail.dart file should be adjusted for yahoo.

Any help is appreciated.

Thank you.

**Comment by close2** [comment]
Hi,

I am not sure I understand.  There is already a yahoo.dart file.  Are its values incorrect?

**Comment by 1Fenix** [comment]
I'm not sure. 
The instructions say that you need to copy the gmail.dart file code to yahoo.dart and adjust the code for yahoo, and that's where I get lost. As I understand the yahoo.dart file that is there is only as a small example of how it should be done. 
So any help would be great.

**Comment by close2** [comment]
Hello 1Fenix.

There is already a yahoo.dart file.  Simply replace every `gmail` in your code with `yahoo`.

**Comment by 1Fenix** [comment]
Thank you close2, but I already tried that.
Did you run it successfully?
 I'll try it some more . I followed the instructions, but maybe I did something wrong,

**Comment by close2** [comment]
Can you please enable debugging and post the output here.
Please remove sensitive information!

```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```

**Comment by schneiti** [comment]
@1Fenix If the thrown exception had the message: ```Socket was closed even though a response was expected.``` PR #231 might be the solution to your issue.

**Comment by close2** [comment]
Hoping that PR #231 fixed this issue.
Please reopen, if not.
