### ISSUE TITLE
html template

### ISSUE THREAD

**Issue by CodeRound** [kaisellgren/mailer#230]
i am trying to send large html content then mailer not able to send mail

`<html>
  <body>
    <p style="text-align: center">
      <img
        alt=""
        src="https://iovrvfhub.org/assets/images/logo.png"
        style="height: 144px; width: 131px"
      />
    </p>

    <p style="text-align: center">
      <a href="https://iovrvfhub.org/">VISIT SITE</a>&nbsp; &nbsp;|&nbsp;
      &nbsp;<a href="https://www.institutionofvaluers.net/gallery">SHOWROOM</a
      >&nbsp; &nbsp;|&nbsp; &nbsp;<a href="https://iovrvfhub.org/contact_us"
        >CONTACT US</a
      >
    </p>

    <p style="text-align: center">
      <a href="https://iovrvfhub.org/contact_us"
        ><img
          alt=""
          src="https://img1.niftyimages.com/_7r/m-g/5wy?txt=Satyam"
          style="height: 567px; width: 600px"
      /></a>
    </p>

    <p style="text-align: center">
      <span style="font-size: 22px"
        ><span style="font-family: Verdana, Geneva, sans-serif"
          >It&#39;s a great journey with you,</span
        ></span
      >
    </p>

    <h2 style="text-align: center"><strong>Have a fantastic day</strong></h2>

    <h2 style="text-align: center">from IOVRVF family</h2>

    <p style="text-align: center">
      Missing out on IOVRVF emails? Be sure to add us to your primary inbox.<br />
      This email was sent by IOVRVF
    </p>

    <p style="text-align: center">
      ( Plot No.3, 2nd Floor, Parwana Road, Pitampura Delhi-110034, India).<br />
      If you don&#39;t want to receive this type of email in the future,
      please&nbsp;<a
        href="https://iovrvfhub.org/contact_us"
        rel="noopener"
        target="_blank"
        >unsubscribe</a
      >.
    </p>
  </body>
</html>
`

this is the html content

**Comment by close2** [comment]
Can you please enable debugging and post the output here.
Please remove sensitive information!

```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```

**Comment by CodeRound** [comment]
the gmail server blocked my html content.that's why my emails not land in inbox.
i changed my html structure and now it work fine

**Comment by close2** [comment]
thansk for reporting back!
