### ISSUE TITLE
[iOS 16.4] A strange bug.

### ISSUE THREAD

**Issue by cddqssc** [kaisellgren/mailer#233]
In release build mode, the body content is always empty even though I have set the body(body: 'test string')

But everything works fine in debug build mode.(There are no changes to the code between the debug and release builds.)

Android works fine in both release and debug modes.

May I ask if anyone has encountered a similar problem?([flutter_email_sender](https://github.com/sidlatau/flutter_email_sender) has the same problem.)

**Comment by close2** [comment]
Hi @cddqssc !

Please try the debug output in your release build.

```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```
