### ISSUE TITLE
Optional _doAuthentication()

### ISSUE THREAD

**Issue by pst9354** [kaisellgren/mailer#234]
Hi,

We have a mail server that doesn't allow authentication (ip-locked, behind firewall, etc).

I just made a quick and dirty change to fix this issue (see below).
Is there something you could support for the next release?

--- 

In smtp_client.dart (line 129)

Original:
```
    // Authenticate
      await _doAuthentication(c);

```
Our code:
```
    // Authenticate
    bool bSkip = false;
    if (smtpServer.username == null) {
      bSkip = true;
    } else {
      if (smtpServer.username!.isEmpty) {
        bSkip = true;
      }
    }

    if (!bSkip) {
      await _doAuthentication(c);
    }
```

**Comment by close2** [comment]
This should already work with the existing code.
`_doAuthentication` does check, if username and password is set:
```dart
  if (c.server.username != null && c.server.password != null) {
    loginResp = await _doAuthLogin(c);
  } else if (c.server.xoauth2Token != null) {
    loginResp = await _doAuthXoauth2(c);
  }
```
The difference to your code is, that you skip the authentication also if the username `isEmpty`.

I would need to research if SMTP allows empty usernames.  If not, adding the check is of course no problem.

(To avoid unnecessary research, I'll wait for your feedback, if this really is your problem.)

**Comment by pst9354** [comment]
Thanks for the above.
Setting username and password to null, worked out fine.
