### ISSUE TITLE
send email TO Yahoo email address will receive error message [554 message not allowed]

### ISSUE THREAD

**Issue by TONYCHOU81905** [kaisellgren/mailer#235]
Hi ,

Recently, every time I send a letter to Yahoo's mailbox, I will receive an error letter, which says "554 Message not allowed - [299]".
Does anyone face this problem before, I couldn't send email to any yahoo mailbox now...

Thanks!

**Comment by close2** [comment]
Hi @TONYCHOU81905 

Is this something others could possibly encounter as well?

If yes, what was the problem?
