### ISSUE TITLE
Flutter Mailer

### ISSUE THREAD

**Issue by shahryfaisal** [kaisellgren/mailer#247]
Sending mail works on iOS, works on an emulator but not on a physical android device

**Comment by close2** [comment]
Please enable debug logs and provide more information:

```dart
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```

**Comment by busslina** [comment]
Seems more a network issue that a mailer issue

**Comment by close2** [comment]
I will close this issue for now.

Feel free to reopen, if more log output indicates a bug in the library.
