### ISSUE TITLE
base64 encoded lines are too long

### ISSUE THREAD

**Issue by isoos** [kaisellgren/mailer#257]
SpamAssasin marks the 80-character long lines as suspicious, see report here: https://github.com/dart-lang/pub-dev/issues/7833

I think the encoding happens here: https://github.com/kaisellgren/mailer/blob/cbac7ec8a377a60bf4adc063219cf8bf53e1650b/lib/src/smtp/internal_representation/ir_content.dart#L32

The const is defined here:
https://github.com/kaisellgren/mailer/blob/cbac7ec8a377a60bf4adc063219cf8bf53e1650b/lib/src/smtp/internal_representation/internal_representation.dart#L21

The wikipedia page suggest that encoded line shouldn't be longer than 76 characters:
https://en.wikipedia.org/wiki/Base64

@kaisellgren: Is there any specific need for the 80-character limit, or can we just reduce it to 76?

**Comment by close2** [comment]
@isoos  Thanks for the report

**Comment by isoos** [comment]
@close2: thank you!
