### ISSUE TITLE
Crypto dependencies

### ISSUE THREAD

**Issue by Kleak** [kaisellgren/mailer#27]
Why in the commit [8347844](https://github.com/kaisellgren/mailer/commit/da5b83cb5032929277860ea4b303e716dd57b051) the crypto constraint version is reduced to only crypto version 0.9.0

Please make an update with crypto constraint '>=0.9.2 <3.0.0' and please merge #26

**Comment by danrubel** [comment]
That was a short term fix to get things working again in the simplest manner.
I've [loosened crypto requirements and fixed the code](https://github.com/kaisellgren/mailer/commit/9221b75ed26a098a0af4ac984c8364535a522b8a) in a step towards publishing mailer 1.1.0.

Please reopen if this does not address your concerns.
