### ISSUE TITLE
completer completes twice

### ISSUE THREAD

**Issue by d3v-cl** [kaisellgren/mailer#28]
```
Unhandled exception:
Bad state: Future already completed
#0      _Completer.completeError (dart:async/future_impl.dart:21)
#1      SmtpClient.send.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:mailer/src/smtp/smtp_client.dart:108:21)
```

In smtp_client.dart (line 108) onError is called even though the sending was successful.

In my case the error was: `Error: 421 mailhost lost input connection`

Please guard the onError with: `if (!completer.isCompleted) {}`

**Comment by close2** [comment]
Further debuggin revealed that this error (421) is sent after the 2xx ok part and could be ignored.
(It might be an incorrect configuration with spamassassin)
