### ISSUE TITLE
Text is not encoded or escaped.

### ISSUE THREAD

**Issue by close2** [kaisellgren/mailer#32]
If your text contains \r\n.\r\n everything after this dot is lost!

Also you specify 7bit encoding without converting anything.

This library currently only works correctly if you send ASCII characters as text.

I am currently rewriting the library.  So no fast PR to fix this issue.

**Comment by close2** [comment]
If a user of this library injects unverified data into the text the user might become an open relay:
```
 var envelope = new Envelope()
    ..from = '$username@gmail.com'
    ..recipients.add(to)
    ..subject = 'Test Dart Mailer library :: ${new DateTime.now()}'
    ..text = 'This is the plain text\r\n.\r\nMAIL FROM:<some@test.com>\r\nRCPT TO:<someOther@test.com>\r\nDATA\r\n' +
        'Subject: some SPAM\r\nFrom: some@test.com\r\nTo: someOther@test.com\r\n\r\n'
        + 'Spam text'
 ```

Most (all?) smtp servers will abort with a 554 SMTP synchronization error.  However.  If the text has the exact right length so that the dot is send in one package the latency might be enough for this to work.

In any case.  I wouldn't test it.

**Comment by kaisellgren** [comment]
Would you like me to add you as a contributor with push and release rights?

**Comment by close2** [comment]
Please take a look at my current rewrite branch https://github.com/close2/mailer/tree/rewrite
Especially: https://github.com/close2/mailer/blob/rewrite/lib/src/smtp/smtp_client.dart

If you think that this goes into the right direction: Yes please.

(Note that you would need to add me as uploader on pub.dartlang if you want me to update releases there as well.  `pub uploader ...`)
