### ISSUE TITLE
convert input to canonical form

### ISSUE THREAD

**Issue by close2** [kaisellgren/mailer#37]
we should convert text input into a canonical form.  Eols should '\r\n' no matter which operating system.

from rfc 2049:

    (2)   Conversion to canonical form.

          The entire body, including "out-of-band" information
          such as record lengths and possibly file attribute
          information, is converted to a universal canonical
          form.  The specific media type of the body as well as
          its associated attributes dictate the nature of the
          canonical form that is used.  Conversion to the proper
          canonical form may involve character set conversion,
          transformation of audio data, compression, or various
          other operations specific to the various media types.
          If character set conversion is involved, however, care
          must be taken to understand the semantics of the media
          type, which may have strong implications for any
          character set conversion, e.g. with regard to
          syntactically meaningful characters in a text subtype
          other than "plain".

          For example, in the case of text/plain data, the text
          must be converted to a supported character set and
          lines must be delimited with CRLF delimiters in
          accordance with RFC 822.  Note that the restriction on
          line lengths implied by RFC 822 is eliminated if the
          next step employs either quoted-printable or base64
          encoding.

**Comment by butlermatt** [comment]
In addition to this, we should also abide by line limit requirements and suggestions.
See this section
https://tools.ietf.org/html/rfc5322#section-2.1.1 (note that RFC5322 supersedes RFC 822 and should be referenced instead)

**Comment by close2** [comment]
The 1000 characters limit are unfortunately necessary.

I am however not really persuaded regarding the 78 character line limit.
It's not that hard to split lines using QuotedPrintable and =.  All email clients will concatenate the lines and display the text as if there was a long line anyways.

Should we really add additional encoded characters if somebody watches the source of an email?

I really hope that the next revision will remove this suggestion (and also remove add a suggestion to SMTP servers to allow 1000+ lines).

**Comment by butlermatt** [comment]
@close2 Thanks for the feedback. I've sent @kaisellgren an e-mail regarding the status of the project and if he would be interested in passing the repo over to another maintainer (myself mentioned in the e-mail) as there are a few other bug fixes I need to address for my own projects. I just thought I'd let you know  as I see you have a couple of PR's here as well.

I'll also cc @tomyeh as I know he created a fork as well for some things he needed implemented himself as well.

**Comment by butlermatt** [comment]
As part of this, we need to also consider dot stuffing.

From https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol
> Since a message body can contain a line with just a period as part of the text, the client sends two periods every time a line starts with a period; correspondingly, the server replaces every sequence of two periods at the beginning of a line with a single one. Such escaping method is called dot-stuffing.
