### ISSUE TITLE
verify library content is mime conformant

### ISSUE THREAD

**Issue by close2** [kaisellgren/mailer#38]
From RFC 2049:
- [ ] Always generate a "MIME-Version: 1.0" header field
- [ ] properly label with a content-transfer-encoding
- [ ] string that begins with "=?" and ends with "?=" must be a valid encoded-word (see RFC)

**Comment by kaisellgren** [comment]
Added you as a contributor.

**Comment by d3v-cl** [comment]
thanks.  patches will come soon.
