### ISSUE TITLE
Mailer is treating 354s as errors

### ISSUE THREAD

**Issue by MarcusSmith** [kaisellgren/mailer#41]
I'm getting errors when the `SMTPClient` gets a 354 response, but emails are still sending. I don't think these should be treated as errors:

https://serverfault.com/a/509469

**Comment by close2** [comment]
mailer accepts 354 as a response to `DATA` as shown in the serverfault link:

```
    sendCommand('DATA');
  }

  void _actionData(String message) {
    // The response should be either 354 or 250.
    if (message.startsWith('2') == false && message.startsWith('3') == false)
      throw 'Data command failed: $message';
```

I guess you receive 354 at some other time.
Do you have more information?

**Comment by MarcusSmith** [comment]
I'm getting them when using `SmtpTransport.send(Envelope)` using Gmail.  The email is sent successfully every time, but more than half the time I am getting errors saying that the transport failed with a 354

**Comment by close2** [comment]
more information needed.

closing for now.  Feel free to reopen.
