### ISSUE TITLE
Error running demo for both mailer and mailer 2

### ISSUE THREAD

**Issue by Kones345** [kaisellgren/mailer#42]
Error occurred: type '_AsBroadcastStream<dynamic>' is not a subtype of type 'Stream<Envelope>' where
  _AsBroadcastStream is from dart:async
  Stream is from dart:async
  Envelope is from package:mailer/mailer.dart

I made sure I've used the correct dependencies and downloaded the packages but I can't stop getting this error and I have no idea where this code is. Possibly in the package implementation itself.
Flutter doctor runs fine.
I've upgraded to the latest version of fluter.

**Comment by mhardis** [comment]
I get the same error in the same conditions... Could somebody fix this please ?

**Comment by salehahmedZ** [comment]
@mhardis @Kones345 

in this file 

> mailer-1.1.4/lib/src/smtp/**smtp_client.dart**

Update lines 48 & 48 

```
  SmtpClient(this.options) {
    onIdle = _onIdleController.stream.asBroadcastStream();
    onSend = _onSendController.stream.asBroadcastStream();
  }
```


to be

```
  SmtpClient(this.options) {
    onIdle = _onIdleController.stream.asBroadcastStream().cast();
    onSend = _onSendController.stream.asBroadcastStream().cast();
  }
```

**Comment by anilulak** [comment]
I had the same issue today. Yesterday my code was running and it all was working. After I changed my channel from alpha to beta and upgrade my flutter version, it didn't work. What salehahmedZ suggested works! Thanks!

**Comment by kaisellgren** [comment]
@salehahmedZ Can you email me at kaisellgren@gmail.com?

**Comment by frey1esm** [comment]
@kaisellgren Is a fix pending for this issue?
