### ISSUE TITLE
mailer3 attachment is not working

### ISSUE THREAD

**Issue by NTMS2017** [kaisellgren/mailer#45]
Previously I create an image in mobile temp directory. In Flutter mobile app I try to send this saved picture using mailer3 plugin as a mail. The mail reach the destination, I don't get error but seems lost the attachment in process.

In dart it works very well and send the attachment as well. In flutter I can use the temp directory to show the image in app but cannot be able attache to mail.

The image location is in the temp folder of the device:
**newDekontImage= '/data/user/0/com.myApp.myApp/cache/20180700087.jpg'**

I can show the image using below code in Flutter:
**new FileImage(File('$newDekontImage'),**

**Error:**
E/flutter (21184): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (21184): FileSystemException: Cannot open file, path = '/data/user/0/com.myApp.myApp/app_flutter/20180700087.jpg' (OS Error: No such file or directory, errno = 2)

How to send mail with attachments in Flutter with provided information in this question?

**Comment by NTMS2017** [comment]
I found that if I send to attach mail to private mail the attachment part works, but using my gmail credentials and send mail to gmail user the attachment cant reach

**Comment by close2** [comment]
I don't see how these 2 issues relate.

The error message indicates that your image cannot be opened.

There is no way this is related to credentials.

Could you please verify that you have a valid File handle using: the File.exists function.

Are you able to send any emails at all using the gmail credentials?
Can you send an email with a text attachment using the gmail credentials?

**Comment by NTMS2017** [comment]
First part related to file which I sort out and after that I realise that mail attachment cannot reach destination. Later I found out that if you use outlook 2016 the attachment will not reach to user editor. I am using Mac, linux and win 10. Linux mail editor,  Mac mail editor, gmail web, yahoo web, hotmail web as well as private company web mail can receive the attachment. If I don't use these and try to use and open main using Outlook 2016 I can receive the mail, content but no attachment. Thanks for response

**Comment by close2** [comment]
Did you specify both: text and html?
If yes, could you please try to send only one of those.

[If this is indeed the problem:
As soon as text and html is sent, we specify a content-type alternative.
This is not 100% correct.  We should still use mixed if there are attachments.
See: https://stackoverflow.com/questions/3902455/mail-multipart-alternative-vs-multipart-mixed]
