### ISSUE TITLE
2 different packages?

### ISSUE THREAD

**Issue by seenickcode** [kaisellgren/mailer#62]
Hey thanks for writing this library. I was wondering why there's 3x different package listings. Just curious.

https://pub.dartlang.org/packages/mailer
https://pub.dartlang.org/packages/mailer3

**Comment by close2** [comment]
there was a period of time where mailer was very badly maintained.

mailer2 and mailer3 did have some bug fixes which were not merged into this library.

I tried to integrate all available bug-fixes in version 1.2.* and did a complete rewrite afterwards (2.0.*).

⇒ version 1.2.* obsoletes those packages and version 2 should be even better.


I'll close this issue, when the README summarizes this as well.
