### ISSUE TITLE
Problem: UNKNOWN: Received an exception: After sending null, response did not start with any of: [2]

### ISSUE THREAD

**Issue by Seedorf161** [kaisellgren/mailer#69]
Everything was working fine before not until now that i keep getting this error `Problem: UNKNOWN: Received an exception: After sending null, response did not start with any of: [2]`

please help.

**Comment by close2** [comment]
AFAICT there are only 1 place which could create a `null` command (`After sending null`).

When creating a connection to the server mailer waits for a greeting message (which must start with `2`).  The command in this case is `null`.

Could you please verify that your smtp server is correctly responding with `2xx something` when connecting:
Windows: download [putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) use `raw` as protocol and connect to the smtp server.
Linux: telnet is usually in a package called inetutils.  `telnet smtp-server port`
MacOs: [article how to test smtp in macOs](https://support.sasktel.com/app/answers/detail/a_id/20201/~/using-telnet-to-test-mail-server-connections-in-mac-os-x)

Please paste the response here or send me an email (christian@loitsch.com)

**Comment by close2** [comment]
I have improved the exception in mailer 2.1.2.
The response of the server is now attached to the exception message.

**Comment by close2** [comment]
If this bug still exists please reopen
