### ISSUE TITLE
QQ mail can not work

### ISSUE THREAD

**Issue by CoXier** [kaisellgren/mailer#71]

**Comment by CoXier** [comment]
Here is question link : https://stackoverflow.com/questions/54160800/send-qq-mail-in-dart

**Comment by close2** [comment]
short update:
I have created an account but need to wait 15 days until QQ allows me to send mails using SMTP.

**Comment by close2** [comment]
If you don't mind, you can send me your details to: <christian@loitsch.com>

I might log into the web-interface to verify that SMTP is enabled.
I promise not to read any mails.

**Comment by close2** [comment]
The smtp-server of qq requires ssl.

I've added a qq server definition.

```
import 'package:mailer/smtp_server.dart';

var qqSmtpServer = qq(usern, pw);
```

should work now.
