### ISSUE TITLE
how to send mail using my company mail server?

### ISSUE THREAD

**Issue by NTMS2017** [kaisellgren/mailer#75]
I am using my gmail account and I can sent a mail in Flutter with no problem. but I cannot use my company mail to send mail in flutter. How to send mail using my company mail server?

**Comment by close2** [comment]
instead of `gmail(username, password)` create your own `SmtpServer` definition:
`'package:mailer/smtp_server.dart'`
`final smtpServer = new SmtpServer('smtp.domain.com');`

See the named arguments of SmtpServer for further configuration options.
