### ISSUE TITLE
Privacy data inside Exception message

### ISSUE THREAD

**Issue by pjkroll** [kaisellgren/mailer#79]
If you use something like Crashlitics it could break the privacy policy:
```
Future<Capabilities> _doEhlo(Connection c) async {
    //...

   if (!loginResp.responseCode.startsWith('2')) {
      throw new SmtpClientAuthenticationException(
          'Incorrect username ($username) / password');
    }
}
```

**Comment by close2** [comment]
I will remove the username from the exception.
Do you know of any possible privacy issues for logging?
Is it ok to output the username using a logging statement?

**Comment by pjkroll** [comment]
It is probably ok to put username inside logs, especially inside debug logs. But I think that if you don't write real username and just 'username', it gives you enough info about the error, and it is less risky. 
  
Of course I would never put an sort of privacy data inside an exception: email, IP, ID...
