### ISSUE TITLE
Implement OAUTH2  [How to send the email in a "more secure" way]

### ISSUE THREAD

**Issue by crushman1** [kaisellgren/mailer#80]
Hello, im not sure if this has already been answered but how do you make a more secure connection with gmail? the reason i asked is when i use gmail to send the emails automatically i get a reply from gmail saying " A suspicious app was blocked from accessing your account". Now i know i can simply disable this in the security tab on gmail but i would prefer not doing this and i would also prefer not asking my users to do this. 
So what exactly is this security function looking for and how do i add it into my sendmail function so that gmail acknowledges the app as a "secure app" and allows the emails through?

**Comment by close2** [comment]
I think we would need to implement OAUTH2.

The code for the authentication is pretty easy:
https://developers.google.com/gmail/imap/xoauth2-protocol

To obtain a secret is more difficult, but a library already exists:
https://github.com/dart-lang/googleapis_auth

Here is an example in python:
https://github.com/google/gmail-oauth2-tools/wiki/OAuth2DotPyRunThrough

**Comment by GauravPatni** [comment]
Hi ,

any update on this?

I am also facing the same issue. if this feature is added then please share code example. 

Thanks 

Gaurav

**Comment by close2** [comment]
Version 3 (currently in my dev tree) will have the possibility to authenticate with XOAUTH2.
However managing the tokens is outside the scope of the `mailer` library.

I will try to implement a working demo which uses:
https:/https://github.com/dart-lang/googleapis_auth/github.com/dart-lang/googleapis_auth

**Comment by close2** [comment]
short update.
I have managed to retrieve and use oauth2 tokens.
I will need to find time to document the usage, but this feature should be available pretty soon.
