### ISSUE TITLE
How to format the html tag?

### ISSUE THREAD

**Issue by NTMS2017** [kaisellgren/mailer#84]
I am using Brackets to design basic HTML Page so I can modify mailer plugin html part.
When I look at the example only "h1, n, >" used. I like to learn if I can insert my own html part as shown below. If not what is the best way to  format the html tag in mailer plugin?

```
html>
 <!-- SEND VIA EMAIL -->    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>GETTING STARTED WITH BRACKETS</title>
        <meta name="description" content="An interactive getting started guide for Brackets.">
        <link rel="stylesheet" href="main.css">
    </head>
  
    <body>
        
        <h2>My Company Name</h2>
        <h3>Registration</h3>
        <p>
            Welcome to Brackets, a modern open-source code editor that understands web design.
        </p>
         <ul>
                <li><strong>User Name</strong> John</li>
                <li><strong>User Surname</strong> Doo</li>
         </ul>
        <h3>Front Picture:</h3>
        <a><img alt="A screenshot showing CSS Quick Edit" src="screenshots/quick-edit.png" height="300" width="400"/></a>
        <h3>Back Picture:</h3>
        <a><img alt="A screenshot showing CSS Quick Edit" src="screenshots/quick-edit.png" height="300" width="400"/></a>       
    </body>
html>
```

**Comment by close2** [comment]
Please see
https://stackoverflow.com/questions/52672186/how-to-send-a-complicated-email-with-flutter-mailer-package/52793020#52793020
where I have answered a similar question.

Note that writing html for mails is quite complicated.  You definitely should use an editor, which is build for this.  We use mjml in our company and replace `$$TEXT_PLACE_HOLDERS$$` as explained in the stackoverflow link.

**Comment by NTMS2017** [comment]
Thank you very much 👍

**Comment by NTMS2017** [comment]
Works perfectly, like you said. Thank you very much for this plugin and all the support you provide for us.
