### ISSUE TITLE
catchException not available as specified in the documentation

### ISSUE THREAD

**Issue by friebetill** [kaisellgren/mailer#90]
The README specifies that the `catchExceptions` parameter is available from the `mailer.dart` file.
```dart
final sendReports = await send(message, smtpServer, catchExceptions: false);
```
But this is incorrect, the parameter can only be changed in the class `SmtpClient`. Dart recommends to not import implementation files from a package, so we should not import the SmtpClient. Would suggest to make the parameter also available in `mailer.dart`. If that makes sense, I'll do a PR.

**Comment by close2** [comment]
Thanks for reporting **and offering a PR**.

I am currently working on version 3, so adding this flag didn't take me long.
