### ISSUE TITLE
No access to the custom exceptions

### ISSUE THREAD

**Issue by friebetill** [kaisellgren/mailer#92]
It would be useful if all of the library's own exceptions (all children of `SmtpClientException`) were public so that one could catch them and handle them. But I'm not sure what the recommendation of Dart or Flutter is. 

Btw. super that you specify which exceptions can be thrown in the `send` method of `SmtpClient`.

Can also submit the PR, would there probably only move the file `exceptions.dart` into the root folder or export the `exceptions.dart` file.

**Comment by close2** [comment]
I will probably move the exceptions into the root folder.
Expect a new release by the end of the week.

**Comment by close2** [comment]
I am not 100% sure that all exceptions are listed.  It's possible that for instance a NullPointerException is also thrown in case message is incorrectly filled.
The mentioned exceptions are however those which are probably of interest.  I will rephrase the documentation to make this clear.
