### ISSUE TITLE
Feature Request, be able to have an HTML header from assets images

### ISSUE THREAD

**Issue by BND10706** [kaisellgren/mailer#93]
I want to email with a header image from my assets images.

**Comment by close2** [comment]
This should already be possible.
AFAIK you can open assets `File file = new File('./assets/image.jpeg'');`
Then add the file as an inline attachment. (`new FileAttachment(file)..cid=yourCid..location=Location.inline;`)
```
/**
 * Represents a single email attachment.
 *
 * You may specify a [File], a [Stream] or just a [String] of [data].
 * [cid] allows you to specify the content id.
 *
 * When [location] is set to [Location.inline] The attachment (usually image)
 * can be referenced using:
 * `cid:yourCid`.  For instance: `<img src="cid:yourCid" />`
 */
abstract class Attachment {
```

You will have to write your own corresponding html (or even better use something like mjml).

I will try to improve the documentation to make this feature more obvious.

If this is not the feature you are looking for please reopen.
