### ISSUE TITLE
Invalid username passsword

### ISSUE THREAD

**Issue by monish152** [kaisellgren/mailer#95]
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Incorrect username / password

I am getting above error. I used same gmail example provided and changed my email and password. But I am getting above error

**Comment by close2** [comment]
Please enable debugging output:
```
    Logger.root.level = Level.ALL;
    Logger.root.onRecord.listen((LogRecord rec) {
      print('${rec.level.name}: ${rec.time}: ${rec.message}');
    });
```

Does any other mail program work?  Gmail requires you to allow insecure applications for SMTP to work.

**Comment by close2** [comment]
I've written an example on how to use gmail with XOAUTH2:
https://github.com/kaisellgren/mailer/tree/master/example/gmail_xoauth2

You will need version 3.+

Please reopen if the problem still exists.
